version: "3"

tasks:

  build:
    desc: Build the MMW library
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ && make

  build:linux:broker:
    desc: Build the MMW library with the broker
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON && make

  build:win:broker:
    desc: Build the MMW library with the broker
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake && make

  build:linux:example:
    desc: Build the MMW library with the broker and sample apps
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_SAMPLE_APPS=ON && make

  build:win:example:
    desc: Build the MMW library with the broker and sample apps on Windows
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_SAMPLE_APPS=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Unix Makefiles" && make

  build:linux:python:
    desc: Build the MMW library with the Python language binding
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_PYTHON_MODULE=ON && make
      - cd ./python && python3 -m pip install -r ../requirements.txt && python3 -m build && python3 -m pip install dist/*.whl

  build:win:python:
    desc: Build the MMW library with the Python language binding
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_SAMPLE_APPS=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_PYTHON_MODULE=ON -G "Unix Makefiles" && make -j
      # - cd ./python && python -m pip install -r ../requirements.txt && python -m build . --wheel && python -m pip install dist/*.whl

  build:linux:all:
    desc: Build the MMW library with the broker, sample apps, and Python language binding
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_SAMPLE_APPS=ON -DBUILD_PYTHON_MODULE=ON && make
      - cd ./python && python3 -m pip install -r ../requirements.txt && python3 -m build && python3 -m pip install dist/*.whl

  build:win:all:
    desc: Build the MMW library with the broker, sample apps, and Python language binding
    cmds:
      - mkdir -p build/
      - cd build/ && cmake ../ -DBUILD_BROKER=ON -DBUILD_SAMPLE_APPS=ON -DBUILD_PYTHON_MODULE=ON && make
      - cd ./python && python3 -m pip install -r ../requirements.txt && python3 -m build && python3 -m pip install dist/*.whl

  clean:
    desc: Clean the build directory
    cmds:
      - rm -rf build/

  docs:
    desc: Build Doxygen + Sphinx documentation
    cmds:
      - doxygen Doxyfile
      - task: sphinx

  sphinx:
    cmds:
      - cd docs && python -m sphinx -b html source build/html

  docs:clean:
    desc: Clean generated documentation
    cmds:
      - rm -rf docs/build
      - rm -rf docs/doxygen/xml
